version: '3'
services:
  traefik:
    image: traefik:v1.4-alpine
    command: --web --docker
    ports:
      - "80:80"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
  frontend:
    image: ir2sora/present-constructor-frontend:1.5.0-SNAPSHOT
    depends_on:
      - backend
    labels:
      - "traefik.backend=frontend"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
  backend:
    image: temp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/opt/h2-data/presents;AUTO_SERVER=TRUE
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASS
    ports:
      - "8080:8080"
    volumes:
      - ${DB_DATA_PATH}:/opt/h2-data
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=PathPrefix:/api/,/oauth/"
      - "traefik.port=8080"
