backend_defaults: &backend_defaults
  docker:
    - image: circleci/openjdk:11.0.2
  working_directory: ~/present-constructor/backend

frontend_defaults: &frontend_defaults
  docker:
    - image: circleci/node:10.16.0-browsers
  working_directory: ~/present-constructor/frontend

version: 2
jobs:
  build_backend:
    <<: *backend_defaults

    steps:
      - checkout:
          path: ~/present-constructor
      - restore_cache:
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - run: ./gradlew test -i

      - save_cache:
          paths:
            - ~/.gradle
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: ~/present-constructor/backend
          paths:
            - ./*

  build_backend_docker:
    <<: *backend_defaults

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: ~/present-constructor/backend

      - restore_cache:
          key: present-constructor-backend-{{ checksum "build.gradle" }}

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./gradlew jib -i

      - save_cache:
          paths:
            - ~/.gradle
          key: present-constructor-backend-{{ checksum "build.gradle" }}

  build_frontend:
    <<: *frontend_defaults

    steps:
      - checkout:
          path: ~/present-constructor

      - restore_cache:
          key: present-constructor-frontend-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: present-constructor-frontend-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run: yarn run test --no-watch
      - run: yarn run lint
      - run: yarn run build --prod

      - persist_to_workspace:
          root: ~/present-constructor/frontend
          paths:
            - ./*

  build_frontend_docker:
    <<: *frontend_defaults

    steps:
      - setup_remote_docker

      - attach_workspace:
          at: ~/present-constructor/frontend

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: yarn run docker-build
      - run: yarn run docker-push

workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_backend_docker:
          requires:
            - build_backend

      - build_frontend
      - build_frontend_docker:
          requires:
            - build_frontend
