spring:
  application.name: present-constructor
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/presents
    username: test
    password: test
    properties:
      sslMode: verify-full

sentry.dsn: ''
