name: frontend build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock
      - run: yarn install --immutable
      - run: yarn run lint
      - run: yarn run check
      - run: yarn run build
