/*
 * This file is generated by jOOQ.
*/
package ru.home.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.home.db.tables.Candy;
import ru.home.db.tables.FlywaySchemaHistory;
import ru.home.db.tables.Present;
import ru.home.db.tables.PresentItem;
import ru.home.db.tables.records.CandyRecord;
import ru.home.db.tables.records.FlywaySchemaHistoryRecord;
import ru.home.db.tables.records.PresentItemRecord;
import ru.home.db.tables.records.PresentRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>presents</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5",
        "schema version:1"
    },
    date = "2018-02-23T09:15:27.173Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CandyRecord> KEY_CANDY_PRIMARY = UniqueKeys0.KEY_CANDY_PRIMARY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<PresentRecord> KEY_PRESENT_PRIMARY = UniqueKeys0.KEY_PRESENT_PRIMARY;
    public static final UniqueKey<PresentItemRecord> KEY_PRESENT_ITEM_PRIMARY = UniqueKeys0.KEY_PRESENT_ITEM_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PresentItemRecord, PresentRecord> PRESENT_ITEM_IBFK_1 = ForeignKeys0.PRESENT_ITEM_IBFK_1;
    public static final ForeignKey<PresentItemRecord, CandyRecord> PRESENT_ITEM_IBFK_2 = ForeignKeys0.PRESENT_ITEM_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CandyRecord> KEY_CANDY_PRIMARY = Internal.createUniqueKey(Candy.CANDY, "KEY_candy_PRIMARY", Candy.CANDY.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<PresentRecord> KEY_PRESENT_PRIMARY = Internal.createUniqueKey(Present.PRESENT, "KEY_present_PRIMARY", Present.PRESENT.ID);
        public static final UniqueKey<PresentItemRecord> KEY_PRESENT_ITEM_PRIMARY = Internal.createUniqueKey(PresentItem.PRESENT_ITEM, "KEY_present_item_PRIMARY", PresentItem.PRESENT_ITEM.PRESENT_ID, PresentItem.PRESENT_ITEM.CANDY_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<PresentItemRecord, PresentRecord> PRESENT_ITEM_IBFK_1 = Internal.createForeignKey(ru.home.db.Keys.KEY_PRESENT_PRIMARY, PresentItem.PRESENT_ITEM, "present_item_ibfk_1", PresentItem.PRESENT_ITEM.PRESENT_ID);
        public static final ForeignKey<PresentItemRecord, CandyRecord> PRESENT_ITEM_IBFK_2 = Internal.createForeignKey(ru.home.db.Keys.KEY_CANDY_PRIMARY, PresentItem.PRESENT_ITEM, "present_item_ibfk_2", PresentItem.PRESENT_ITEM.CANDY_ID);
    }
}
