/*
 * This file is generated by jOOQ.
*/
package ru.home.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.home.db.tables.Candy;
import ru.home.db.tables.FlywaySchemaHistory;
import ru.home.db.tables.Present;
import ru.home.db.tables.PresentItem;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5",
        "schema version:1"
    },
    date = "2018-02-23T09:15:27.173Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Presents extends SchemaImpl {

    private static final long serialVersionUID = 1697506344;

    /**
     * The reference instance of <code>presents</code>
     */
    public static final Presents PRESENTS = new Presents();

    /**
     * The table <code>presents.candy</code>.
     */
    public final Candy CANDY = ru.home.db.tables.Candy.CANDY;

    /**
     * The table <code>presents.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = ru.home.db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>presents.present</code>.
     */
    public final Present PRESENT = ru.home.db.tables.Present.PRESENT;

    /**
     * The table <code>presents.present_item</code>.
     */
    public final PresentItem PRESENT_ITEM = ru.home.db.tables.PresentItem.PRESENT_ITEM;

    /**
     * No further instances allowed
     */
    private Presents() {
        super("presents", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Candy.CANDY,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Present.PRESENT,
            PresentItem.PRESENT_ITEM);
    }
}
