/*
 * This file is generated by jOOQ.
 */
package ru.home.db;


import javax.annotation.Generated;

import ru.home.db.tables.Candy;
import ru.home.db.tables.FlywaySchemaHistory;
import ru.home.db.tables.Present;
import ru.home.db.tables.PresentItem;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2",
        "schema version:PUBLIC_1.5.0"
    },
    date = "2018-10-16T00:20:10.442Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.candy</code>.
     */
    public static final Candy CANDY = ru.home.db.tables.Candy.CANDY;

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = ru.home.db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>PUBLIC.present</code>.
     */
    public static final Present PRESENT = ru.home.db.tables.Present.PRESENT;

    /**
     * The table <code>PUBLIC.present_item</code>.
     */
    public static final PresentItem PRESENT_ITEM = ru.home.db.tables.PresentItem.PRESENT_ITEM;
}
